install etc

diff --git a/bin/npm-install b/bin/npm-install
--- a/bin/npm-install
+++ b/bin/npm-install
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Summary: Install a Node version using the node-build plugin
+# Summary: Install a Node version using the npmenv plugin
 #
 # Usage: ndenv install [-f|--force] [-k|--keep] [-v|--verbose] <version>
 #        ndenv install [-f|--force] [-k|--keep] [-v|--verbose] <definition-file>
@@ -13,15 +13,15 @@
 #   -v/--verbose     Verbose mode: print compilation status to stdout
 #
 # For detailed information on installing Node versions with
-# node-build, including a list of environment variables for adjusting
-# compilation, see: https://github.com/riywo/node-build#usage
+# npmenv, including a list of environment variables for adjusting
+# compilation, see: https://github.com/riywo/npmenv#usage
 #
 set -e
 [ -n "$NDENV_DEBUG" ] && set -x
 
 # Provide ndenv completions
 if [ "$1" = "--complete" ]; then
-  exec node-build --definitions
+  exec npmenv --definitions
 fi
 
 if [ -z "$NDENV_ROOT" ]; then
@@ -29,7 +29,7 @@ if [ -z "$NDENV_ROOT" ]; then
 fi
 
 # Load shared library functions
-eval "$(node-build --lib)"
+eval "$(npmenv --lib)"
 
 usage() {
   # We can remove the sed fallback once rbenv 0.4.0 is widely available.
@@ -39,7 +39,7 @@ usage() {
 
 definitions() {
   local query="$1"
-  node-build --definitions | grep -F "$query" || true
+  npmenv --definitions | grep -F "$query" || true
 }
 
 indent() {
@@ -71,7 +71,7 @@ for option in "${OPTIONS[@]}"; do
     VERBOSE="-v"
     ;;
   "version" )
-    exec node-build --version
+    exec npmenv --version
     ;;
   * )
     usage 1
@@ -136,10 +136,10 @@ if [ -n "${NDENV_BUILD_ROOT}" ]; then
   KEEP="-k"
 fi
 
-# Set NODE_BUILD_CACHE_PATH to $NDENV_ROOT/cache, if the directory
+# Set NPMENV_CACHE_PATH to $NDENV_ROOT/cache, if the directory
 # exists and the variable is not already set.
-if [ -z "${NODE_BUILD_CACHE_PATH}" ] && [ -d "${NDENV_ROOT}/cache" ]; then
-  export NODE_BUILD_CACHE_PATH="${NDENV_ROOT}/cache"
+if [ -z "${NPMENV_CACHE_PATH}" ] && [ -d "${NDENV_ROOT}/cache" ]; then
+  export NPMENV_CACHE_PATH="${NDENV_ROOT}/cache"
 fi
 
 # Default NDENV_VERSION to the globally-specified Node version.
@@ -156,9 +156,9 @@ cleanup() {
 
 trap cleanup SIGINT
 
-# Invoke `node-build` and record the exit status in $STATUS.
+# Invoke `npmenv` and record the exit status in $STATUS.
 STATUS=0
-node-build $KEEP $VERBOSE "$DEFINITION" "$PREFIX" || STATUS="$?"
+npmenv $KEEP $VERBOSE "$DEFINITION" "$PREFIX" || STATUS="$?"
 
 # Display a more helpful message if the definition wasn't found.
 if [ "$STATUS" == "2" ]; then
@@ -169,11 +169,11 @@ if [ "$STATUS" == "2" ]; then
       echo "$candidates" | indent
     fi
     echo
-    echo "You can list all available versions with \`ndenv install --list'."
+    echo "You can list all available versions with \`ndenv npm install --list'."
     echo
     echo "If the version you're looking for is not present, first try upgrading"
-    echo "node-build. If it's still missing, open a request on the node-build"
-    echo "issue tracker: https://github.com/riywo/node-build/issues"
+    echo "npmenv. If it's still missing, open a request on the npmenv"
+    echo "issue tracker: https://github.com/fand/npmenv/issues"
   } >&2
 fi
 
